name: cellSquito
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - alsa-lib=1.2.13=hb9d3cd8_0
  - argcomplete=3.5.2=pyhd8ed1ab_0
  - argh=0.31.3=pyhd8ed1ab_1
  - augustus=3.5.0=pl5321heb9362c_5
  - bamtools=2.5.2=h077b44d_6
  - bbmap=39.18=he5f24ec_0
  - binutils_impl_linux-64=2.43=h4bf12b8_4
  - biopython=1.85=py310ha75aee5_1
  - blast=2.16.0=h66d330f_4
  - boost-cpp=1.85.0=h3c6214e_4
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py310hf71b8c6_2
  - busco=5.8.2=pyhdfd78af_0
  - bwidget=1.10.1=ha770c72_0
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.1.31=hbcca054_0
  - cairo=1.18.2=h3394656_1
  - cdbtools=0.99=1
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.17.1=py310h8deb56e_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - clustalw=2.1=h9948957_12
  - contourpy=1.3.1=py310h3788b33_0
  - curl=8.12.1=h332b0f4_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dendropy=5.0.6=pyhdfd78af_0
  - diamond=2.1.11=h5ca1c30_1
  - dnspython=2.7.0=pyhff2d567_1
  - emboss=6.6.0=he50b15c_11
  - entrez-direct=22.4=he881be0_0
  - fastp=0.24.0=heae3180_1
  - fasttree=2.1.11=h7b50bb2_5
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.56.0=py310h89163eb_0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - gawk=5.3.1=hcd3d067_0
  - gcc_impl_linux-64=14.2.0=hdb7739f_2
  - gettext=0.23.1=h5888daf_0
  - gettext-tools=0.23.1=h5888daf_0
  - gffutils=0.13=pyh7cba7a3_0
  - gfortran_impl_linux-64=14.2.0=h0ee6e4a_2
  - giflib=5.2.2=hd590300_0
  - gmap=2024.11.20=pl5321hb1d24b7_1
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.13=h59595ed_1003
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=14.2.0=h2ead766_2
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=10.4.0=h76408a6_0
  - hmmer=3.4=h503566f_3
  - hpack=4.1.0=pyhd8ed1ab_0
  - htslib=1.21=h566b1c6_1
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.6.1=pyha770c72_0
  - isa-l=2.31.1=hb9d3cd8_1
  - joblib=1.4.2=pyhd8ed1ab_1
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py310h3788b33_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h27087fc_0
  - libasprintf=0.23.1=h8e693c7_0
  - libasprintf-devel=0.23.1=h8e693c7_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libboost=1.85.0=h0ccab89_4
  - libboost-devel=1.85.0=h00ab1b0_4
  - libboost-headers=1.85.0=ha770c72_4
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=31_he106b2a_openblas
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.12.1=h332b0f4_0
  - libdeflate=1.23=h4ddbbb0_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.6=h2dba641_0
  - libgcc=14.2.0=h767d61c_2
  - libgcc-devel_linux-64=14.2.0=h9c4974d_102
  - libgcc-ng=14.2.0=h69a702a_2
  - libgd=2.3.3=h6f5c62b_11
  - libgettextpo=0.23.1=h5888daf_0
  - libgettextpo-devel=0.23.1=h5888daf_0
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libglib=2.82.2=h2ff4ddf_1
  - libgomp=14.2.0=h767d61c_2
  - libharu=2.4.4=h267a509_0
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.18=h4ce23a2_1
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblzma=5.6.4=hb9d3cd8_0
  - liblzma-devel=5.6.4=hb9d3cd8_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libopenssl-static=3.4.1=hb9d3cd8_0
  - libpng=1.6.47=h943b412_0
  - libsanitizer=14.2.0=hed042b8_2
  - libsqlite=3.49.1=hee588c1_1
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-devel_linux-64=14.2.0=h9c4974d_102
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtiff=4.7.0=hd9ff511_3
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.6=h8d12d68_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lp_solve=5.5.2.11=hd590300_0
  - mafft=7.526=h4bc722e_0
  - make=4.4.1=hb9d3cd8_2
  - matplotlib-base=3.10.1=py310h68603db_0
  - metaeuk=7.bba0d80=pl5321hd6d6fdc_2
  - metis=5.1.0=hd0bcaf9_1007
  - miniprot=0.13=h577a1d6_2
  - mpfr=4.2.1=h90cbb55_3
  - munkres=1.0.7=py_1
  - muscle=3.8.1551=h9948957_8
  - mysql-connector-c=6.1.11=h659d440_1008
  - ncbi-vdb=3.2.0=h9948957_0
  - ncurses=6.5=h2d0b736_3
  - numpy=2.2.3=py310hefbff90_0
  - openjdk=23.0.2=h68779a4_1
  - openjpeg=2.5.3=h5fbd93e_0
  - openssl=3.4.1=h7b32b05_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py310h5eaa309_1
  - pango=1.56.1=h861ebed_0
  - pasta=1.9.2=py310h2eb23f3_3
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.44=hba22ea6_2
  - perl=5.32.1=7_hd590300_perl5
  - perl-apache-test=1.43=pl5321hdfd78af_0
  - perl-app-cpanminus=1.7048=pl5321hd8ed1ab_0
  - perl-archive-tar=2.40=pl5321hdfd78af_0
  - perl-base=2.23=pl5321hdfd78af_2
  - perl-carp=1.38=pl5321hdfd78af_4
  - perl-class-load=0.25=pl5321hdfd78af_1
  - perl-class-load-xs=0.10=pl5321h9f5acd7_6
  - perl-class-method-modifiers=2.13=pl5321hdfd78af_0
  - perl-common-sense=3.75=pl5321hdfd78af_0
  - perl-compress-raw-bzip2=2.201=pl5321h87f3376_1
  - perl-compress-raw-zlib=2.105=pl5321h87f3376_0
  - perl-constant=1.33=pl5321hdfd78af_2
  - perl-cpan-meta-check=0.014=pl5321hdfd78af_1
  - perl-cpan-meta-requirements=2.143=pl5321hdfd78af_0
  - perl-data-optlist=0.113=pl5321ha770c72_0
  - perl-dbi=1.643=pl5321hec16e2b_1
  - perl-devel-globaldestruction=0.14=pl5321hdfd78af_1
  - perl-devel-overloadinfo=0.007=pl5321hdfd78af_0
  - perl-devel-stacktrace=2.04=pl5321hdfd78af_1
  - perl-dist-checkconflicts=0.11=pl5321hdfd78af_3
  - perl-encode=3.19=pl5321hec16e2b_1
  - perl-eval-closure=0.14=pl5321h9f5acd7_6
  - perl-exporter=5.72=pl5321hdfd78af_2
  - perl-exporter-tiny=1.002002=pl5321hdfd78af_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-file-path=2.18=pl5321hd8ed1ab_0
  - perl-file-temp=0.2304=pl5321hd8ed1ab_0
  - perl-file-util=4.201720=pl5321hdfd78af_0
  - perl-file-which=1.24=pl5321hd8ed1ab_0
  - perl-getopt-long=2.58=pl5321hdfd78af_0
  - perl-inc-latest=0.500=pl5321ha770c72_0
  - perl-io-compress=2.201=pl5321h503566f_4
  - perl-io-zlib=1.14=pl5321hdfd78af_0
  - perl-json=4.10=pl5321hdfd78af_1
  - perl-json-xs=4.03=pl5321h9948957_4
  - perl-lib=0.63=pl5321hdfd78af_2
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h7b50bb2_4
  - perl-module-build=0.4234=pl5321ha770c72_1
  - perl-module-implementation=0.09=pl5321hdfd78af_3
  - perl-module-metadata=1.000038=pl5321hdfd78af_0
  - perl-module-runtime=0.016=pl5321hdfd78af_2
  - perl-module-runtime-conflicts=0.003=pl5321hdfd78af_1
  - perl-moo=2.005004=pl5321hdfd78af_0
  - perl-moose=2.2202=pl5321hec16e2b_0
  - perl-mro-compat=0.15=pl5321hdfd78af_0
  - perl-package-deprecationmanager=0.17=pl5321hdfd78af_1
  - perl-package-stash=0.40=pl5321h87f3376_1
  - perl-package-stash-xs=0.30=pl5321hb9d3cd8_2
  - perl-parallel-forkmanager=2.03=pl5321hdfd78af_0
  - perl-params-util=1.102=pl5321h9f5acd7_1
  - perl-parent=0.236=pl5321hdfd78af_2
  - perl-pathtools=3.75=pl5321hec16e2b_3
  - perl-role-tiny=2.002004=pl5321hdfd78af_0
  - perl-scalar-list-utils=1.62=pl5321hec16e2b_1
  - perl-storable=3.15=pl5321hec16e2b_3
  - perl-sub-exporter=0.988=pl5321hdfd78af_0
  - perl-sub-exporter-progressive=0.001013=pl5321hdfd78af_1
  - perl-sub-identify=0.14=pl5321hec16e2b_2
  - perl-sub-install=0.928=pl5321hdfd78af_3
  - perl-sub-name=0.21=pl5321hec16e2b_3
  - perl-sub-quote=2.006006=pl5321hdfd78af_0
  - perl-test-fatal=0.016=pl5321hdfd78af_0
  - perl-try-tiny=0.31=pl5321hdfd78af_1
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - perl-version=0.9924=pl5321hec16e2b_2
  - perl-xsloader=0.24=pl5321hd8ed1ab_0
  - perl-yaml=1.30=pl5321hdfd78af_0
  - pillow=11.1.0=py310h7e6dc6c_0
  - pip=25.0.1=pyh8b19718_0
  - pixman=0.44.2=h29eaf8c_0
  - prank=170427=h9948957_1
  - prodigal=2.6.3=h7b50bb2_10
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.22=pyh29332c3_1
  - pyfaidx=0.8.1.3=pyhdfd78af_0
  - pymongo=4.11=py310hf71b8c6_0
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.16=he725a3c_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.1=pyhd8ed1ab_0
  - python_abi=3.10=5_cp310
  - pytz=2024.1=pyhd8ed1ab_0
  - pyvcf3=1.0.3=pyhdfd78af_0
  - qhull=2020.2=h434a139_5
  - r=4.4=r44hd8ed1ab_1008
  - r-base=4.4.3=h9c32bc2_0
  - r-boot=1.3_31=r44hc72bb7e_0
  - r-class=7.3_23=r44h2b5f3a1_0
  - r-cli=3.6.4=r44h93ab643_1
  - r-cluster=2.1.8=r44hb67ce94_0
  - r-codetools=0.2_20=r44hc72bb7e_1
  - r-colorspace=2.1_1=r44hdb488b9_0
  - r-crayon=1.5.3=r44hc72bb7e_1
  - r-ellipsis=0.3.2=r44hb1dbf0f_3
  - r-fansi=1.0.6=r44hb1dbf0f_1
  - r-farver=2.1.2=r44ha18555a_1
  - r-foreign=0.8_88=r44h2b5f3a1_0
  - r-ggplot2=3.5.1=r44hc72bb7e_1
  - r-glue=1.8.0=r44h2b5f3a1_0
  - r-gtable=0.3.6=r44hc72bb7e_0
  - r-isoband=0.2.7=r44ha18555a_3
  - r-kernsmooth=2.23_26=r44h8461fee_0
  - r-labeling=0.4.3=r44hc72bb7e_1
  - r-lattice=0.22_6=r44hb1dbf0f_1
  - r-lifecycle=1.0.4=r44hc72bb7e_1
  - r-magrittr=2.0.3=r44hb1dbf0f_3
  - r-mass=7.3_64=r44h2b5f3a1_0
  - r-matrix=1.7_2=r44h2ae2be5_0
  - r-mgcv=1.9_1=r44h0d28552_1
  - r-munsell=0.5.1=r44hc72bb7e_1
  - r-nlme=3.1_167=r44hb67ce94_0
  - r-nnet=7.3_20=r44h2b5f3a1_0
  - r-pillar=1.10.1=r44hc72bb7e_0
  - r-pkgconfig=2.0.3=r44hc72bb7e_4
  - r-r6=2.6.1=r44hc72bb7e_0
  - r-rcolorbrewer=1.1_3=r44h785f33e_3
  - r-recommended=4.4=r44hd8ed1ab_1007
  - r-rlang=1.1.5=r44h93ab643_0
  - r-rpart=4.1.24=r44h2b5f3a1_0
  - r-scales=1.3.0=r44hc72bb7e_1
  - r-spatial=7.3_18=r44h2b5f3a1_0
  - r-survival=3.8_3=r44h2b5f3a1_0
  - r-tibble=3.2.1=r44hdb488b9_3
  - r-utf8=1.2.4=r44hb1dbf0f_1
  - r-vctrs=0.6.5=r44h0d4f4ea_1
  - r-viridislite=0.4.2=r44hc72bb7e_2
  - r-withr=3.0.2=r44hc72bb7e_0
  - raxml=8.2.13=h7b50bb2_3
  - readline=8.2=h8c095d6_2
  - requests=2.32.3=pyhd8ed1ab_1
  - rnaquast=2.3.0=h9ee0642_0
  - rpsbproc=0.5.0=hd6d6fdc_2
  - samtools=1.21=h96c455f_1
  - sed=4.8=he412f7d_0
  - sepp=4.5.5=py310h9ee0642_2
  - setuptools=75.8.2=pyhff2d567_0
  - simplejson=3.20.1=py310ha75aee5_0
  - six=1.17.0=pyhd8ed1ab_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - spades=4.1.0=haf24da9_0
  - sqlite=3.49.1=h9eae976_1
  - star=2.7.11b=h5ca1c30_5
  - suitesparse=5.10.1=h5a4f163_3
  - sysroot_linux-64=2.17=h0157908_18
  - tar=1.34=hb2e2bae_1
  - tbb=2022.0.0=hceb3a55_0
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h8bc8fbc_6
  - tzdata=2025a=h78e105d_0
  - ucsc-blat=472=h664eb37_1
  - ucsc-fatotwobit=472=h52f6b31_1
  - ucsc-pslsort=469=h664eb37_1
  - ucsc-twobitinfo=472=h664eb37_1
  - unicodedata2=16.0.0=py310ha75aee5_0
  - urllib3=2.3.0=pyhd8ed1ab_0
  - wget=1.21.4=hda4d442_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.5=he73a12e_0
  - xorg-libx11=1.8.11=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xz=5.6.4=hbcc6ac9_0
  - xz-gpl-tools=5.6.4=hbcc6ac9_0
  - xz-tools=5.6.4=hb9d3cd8_0
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.19.0=py310h5764c6d_0
  - zstd=1.5.7=hb8e6e7a_1
prefix: /home/jake/miniconda3/envs/mosquito
